name: Build Flutter APK (Test CI)

on:
  push:
    branches:
      - main   # run whenever you push to main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Flutter clean
        run: flutter clean

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK (debug)
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-debug-apk
          path: build/app/outputs/flutter-apk/app-release.apk